### ISSUE TITLE
Broadcast address is incorrect after executing handle.address().add()

### ISSUE THREAD

**Issue by lambdabear** [little-dude/netlink#42]
After running 
handle
        .address()
        .add(index, IpAddr::V4(Ipv4Addr::new(10, 0, 0, 20)), 24)
        .execute()
        .wait()
        .unwrap();

ip addr show:
inet 10.0.0.20/24 brd 255.255.255.0 scope global secondary enp7s0

But the correct brd should be 10.0.0.255, maybe it is wrong to make the subnet mask a broadcast address.

**Comment by little-dude** [comment]
The problem is probably here: https://github.com/little-dude/netlink/blob/3c3ecba895a2a8653b17279509e9a5f82250aefa/rtnetlink/src/addr/add.rs#L60-L63

I may have misunderstood the `IFA_BROADCAST` attribute.

I'm afk until mid-may though so I won't be able to debug that. However I'll gladly test and review a PR in the meantime.

**Comment by lambdabear** [comment]
Thanks, I have created a PR for this issue.
