### ISSUE TITLE
Generic netlink support?

### ISSUE THREAD

**Issue by joshtriplett** [little-dude/netlink#83]
I'm looking for support for generic netlink messages; do you have any plans to support genl?

(Or, is it already supported and I managed to miss the crate supporting it?)

**Comment by little-dude** [comment]
Hi @joshtriplett,

Currently there's no first class support for genl unfortunately. You can still get it to work because the `netlink-packet-core` provides some of what you'd need (netlink headers in particular, and some helpers to parse netlink messages).

What you'd need to implement yourself atm are the genl message themself, ie all the `genl_` structs. Once you have such a `GenlMessage` type, you can create a [`NetlinkMessage<GenlMessage>`](https://docs.rs/netlink-packet-core/0.2.0/netlink_packet_core/struct.NetlinkMessage.html).

With `NetlinkMessage<GenlMessage>`, you can use [`netlink-proto`](https://docs.rs/netlink-proto/0.4.0/netlink_proto/index.html). This crate provide the netlink protocol implementation for tokio. I have long term plans to make this runtime agnostic, or at least to offer a couple different runtimes via feature flags, but currently only tokio is supported.

Please let me know how I if help further.

Also, note that [`neli`](https://github.com/jbaublitz/neli/blob/master/src/genl.rs) seems to have some support for `genl` already. I don't know how complete it is but it's probably worth checking out :)

**Comment by joshtriplett** [comment]
@little-dude Constructing the generic netlink message was exactly where I was hoping to find some type-safe wrappers for the structures involved. I'm not excited about hand-constructing the structures I'd need. :)

I did try `neli`, but ran into some difficulties.

**Comment by little-dude** [comment]
@joshtriplett genl doesn't seem too complicated, I might give it a shot this week-end. No guarantee though, I'm having little time for open-source these days unfortunately :(

**Comment by joshtriplett** [comment]
@little-dude Thank you! I look forward to trying it if you get the chance.

**Comment by Leo1003** [comment]
The generic netlink support #153  is merged into master. It is one step away from using it through crates.io

**Comment by little-dude** [comment]
This is now available on crates.io: https://crates.io/crates/netlink-packet-generic
