### ISSUE TITLE
Extended ifa flags

### ISSUE THREAD

**Issue by stoically** [little-dude/netlink#84]
Thanks for rtnetlink!

Currently the [`ifa_flags` are hardcoded to `u8`](https://github.com/little-dude/netlink/blob/2c57727a9a277fa4cca12f9e9ecdf9ea36a41064/netlink-packet-route/src/rtnl/constants.rs#L522). Newer kernels support `u32` flags, to allow e.g. setting `IFA_F_MANAGETEMPADDR`.

Just changing to `u32` might not be desired since older kernels don't support that. `iproute2` worked around it by [dynamically switching to `u32`](https://github.com/shemminger/iproute2/commit/8b21f88dd05d72a960ec4170ed49288e8846f578).

I'd be happy to work on a PR if you plan to support extended ifa flags and be interested in how you would like to see support being implemented.

**Comment by little-dude** [comment]
Hi @stoically,

I seems that we're already using `u32` for the flags. See:

- https://github.com/little-dude/netlink/blob/92e2d4c75e230023ddeecd12d2f6ece536a52ca6/netlink-packet-route/src/rtnl/address/nlas/mod.rs#L78
- and https://github.com/little-dude/netlink/blob/92e2d4c75e230023ddeecd12d2f6ece536a52ca6/netlink-packet-route/src/rtnl/address/nlas/mod.rs#L116

So I think the problem is more that this won't work on old kernels. Dynamically switching from between `u32` and `u8` flags sounds like a good idea to support older kernels though, and I'd gladly accept a PR for this.

Could we keep the [`Nla::Flags(u32)`](https://github.com/little-dude/netlink/blob/92e2d4c75e230023ddeecd12d2f6ece536a52ca6/netlink-packet-route/src/rtnl/address/nlas/mod.rs#L27), but upon emitting it check for the necessary length, and emit a simple `u8` if the flags fit, and an `u32` otherwise? For parsing, we just have to check the length field of the NLA to know whether we need to parse an `u8` or an `u32`, so that's a bit easier.

Another option would be to do that non-dynamically: giving a kernel version as a compile flag, and based on that decide on how flags are represented. I've thought of doing that for other parts of the protocol that changed over time. But I'm not sure this is such a good idea.

**Comment by stoically** [comment]
Ah, I've got the [header flags](https://github.com/little-dude/netlink/blob/92e2d4c75e230023ddeecd12d2f6ece536a52ca6/netlink-packet-route/src/rtnl/address/message.rs#L19) and the actual nla ifa_flags confused (and even linked something totally unrelated). You're right - it totally works already. Thanks for the explanation and sorry for the noise. I'm going ahead and closing this issue, since I'd say its solved.

As for supporting older kernels, I'm personally not having that use case, but that sounds like two good approaches. Maybe a dedicated issue for that might make sense.
